--create table Clinic.dimDepartments(
-- department_ID						int primary key,
-- [name]									varchar(30),
--	description]							varchar(300),
--	previous_chairman				varchar(100),
--	chairman_change_date		date,
--	current_chairman					varchar(100),--SCD3
--	previous_assistant				varchar(100),
--	assistant_change_date			date,
--	current_assistant					varchar(100),--SCD3
--	chairman_phone_number	varchar(15),--SCD1
--	assistant_phone_number		varchar(15),--SCD1
--	chairman_room					int,
--	assistant_room						int,
--	reception_phone_number	varchar(15),--SCD1
--	budget									int,
--	additional_info						varchar(200)
--)
--go

--create table Clinic.dimDoctorContracts(
--	doctorContract_ID			int primary key,
--	contract_start_date			date,
--	contract_end_date			date,
--	appointment_portion		int,
--	salary								int,
--	active								bit,
--  active_description                  varchar(50),
--	additional_info					varchar(200) 
--)
--go

--create table Clinic.dimDoctors(
--	doctor_code						int primary key, -- surrogate key
-- doctor_ID								int,
--	doctorContract_ID				int,--SCD2
--  national_code						varchar(15),
--  license_code						varchar(25),
--  first_name							varchar(30),
--  last_name							varchar(75),
--  birthdate								date,
--  phone_number					varchar(25),--SCD1
--	department_ID						int,
--	department_name				varchar(30),
--	education_degree				int, --[1-3]  --SCD2 
--	specialty_description			varchar(100),
--	graduation_date					date,
--	university								varchar(100),
--	gender									varchar(10),
--	religion								varchar(100),
--	nationality							varchar(50),
--	marital_status						bit,
--	marital_status_description	varchar(20), -- 0 for single / 1 for married
--	postal_code							varchar(12),
--	[address]								varchar(200),
--	additional_info						varchar(200),
--	[start_date]							date,
-- end_date								date,
-- current_flag							int,
--	ContractDegree					bit-- 0 -> Contract / 1 -> Degree
--	ContractDegree_description					varchar(50)
--)
--go

--create table Clinic.dimIllnessTypes(
--	illnessType_ID					int primary key,
--	[name]								varchar(50),
--	[description]					varchar(200),
--	related_department_ID	int
--)
--go

--create table Clinic.dimIllnesses(
--	illness_ID					int primary key,
--	[name]						varchar(100),
--	illnessType_ID			int,
--	illnessType_name		varchar(50),
--	scientific_name		varchar(100),
--	special_illness			bit, --0 for not special / 1 for special illnesses
--	killing_status			smallint,
--	killing_description	varchar(100),
--	chronic						bit,
--	chronic_description varchar(100)
--)
--go

--create table Clinic.factTransactionAppointment (
-- patient_code					int,-- surrogate key
-- patient_ID						int,--natural key
--	insurance_ID					int, 
-- insuranceCompany_ID		int,
-- doctor_ID							int,
--	doctorContract_ID			int,
--	department_ID					int,
--	main_detected_illness		int,
--	illnessType_ID					int,
-- TimeKey							int,
--	-------------------------------
--    paid_price						int,
--	real_price							int,
--	insurance_credit				int,
--	doctor_share					int,
--	income								int
--)
--go

--create table Clinic.factDailyAppointment (
--	insuranceCompany_ID		int,
-- doctor_ID							int,
--	doctorContract_ID			int,
--	department_ID					int,
--	main_detected_illness		int,
--	illnessType_ID					int,
-- TimeKey							int,
--	-------------------------------
--	total_paied_price				int,
--	total_real_price				int,
--	total_insurance_credit		int,
--	total_doctor_share			int,
--	total_income					int,
--	number_of_patient			int
--)
--go

--create table Clinic.factMonthlyAppointment (
--	insuranceCompany_ID		int,
-- doctor_ID							int,
--	doctorContract_ID			int,
--	department_ID					int,
-- TimeKey							int,
--	-------------------------------
--	total_paied_price				int,
--	total_real_price				int,
--	total_insurance_credit		int,
--	total_doctor_share			int,
--	total_income					int,
--	number_of_patient			int,
--	max_visit_per_day			int,
--	min_visit_per_day			int,
--	avg_visit_per_day				int,
--)
--go

--create table Clinic.factAccumulativeAppointment (
-- insuranceCompany_ID		int,
-- doctor_ID							int,
--	doctorContract_ID			int,
--	department_ID					int,
--	-------------------------------
--	total_paied_price				int,
--	total_real_price				int,
--	total_insurance_credit		int,
--	total_doctor_share			int,
--	total_income					int,
--	number_of_patient			int,
--	max_visit_per_month		int,
--	min_visit_per_month		int,
--	avg_visit_per_month		int,
--)
--go

--create table factlessPatientIlnesses(
--	patient_ID				int,
--	illness_ID					int,
--	[detection_date]		date,
--	severity					int, --[1-5]
--	additional_info			varchar(200)
--)
--go

--create table Logs(
-- [date]				datetime,
-- table_name     varchar(50),
-- [status]				bit,
-- [description]	varchar(500),
-- affected_rows  int,
--)